# Generated by Django 3.0.7 on 2020-06-22 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import document_storage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('doc_size', models.IntegerField(blank=True, null=True)),
                ('doc_format', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('effect_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.IntegerField()),
                ('document', models.FileField(upload_to=document_storage.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField()),
                ('name', models.TextField()),
                ('doc_size', models.IntegerField(blank=True, null=True)),
                ('doc_format', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('effect_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.TextField()),
                ('document', models.FileField(upload_to=document_storage.models.get_upload_path)),
                ('cur_dock', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='document_storage.Document')),
                ('mentioned_people', models.ManyToManyField(blank=True, to='document_storage.Owner')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='mentioned_people',
            field=models.ManyToManyField(blank=True, to='document_storage.Owner'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
