# Generated by Django 3.0.5 on 2020-04-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='amount_of_mentioned',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='D:\\gitHub\\LocalRegularityDocumentsDatabase\\lrdb_back\\media'),
        ),
    ]
