# Generated by Django 3.0.5 on 2020-04-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='amount_of_mentioned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
