# Generated by Django 3.0.5 on 2020-04-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('effect_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to='D:\\LocalRegulatoryDocumentDB\\media')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mail', models.TextField()),
            ],
        ),
    ]
